/* makegrids.c */

/*
    suko - suko puzzle solver using brute force

    Copyright (c) 2021 Karl Geiger

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/> *

 */

/*
 * Generates the list of possible suko answers. There are 9! possible
 * puzzle grids. Suko solver searches this list for a grid that matches
 * the puzzle's input parameters (clues).
 *
 * Output format is a C header file that's compiled into main program.
 */

#include <stdio.h>

#define PROGRAM "makegrids"
#define VERSION "0.2"

#define swap_i(a, b) \
	do { int t=(a); (a)=(b); (b)=t; } while (0)


#define PERMUTATIONS_MAX 362880  /* == 9! */

int permutation_knt;

void write_file_header();
void permute (int a[], int left, int right);
void write_permutation();
void write_file_trailer();


void main(void) {
	int a[] = {1,2,3,4,5,6,7,8,9};
	int alen = sizeof(a)/sizeof(a[0]);

	permutation_knt= 0;

	write_file_header();

	permute (a, 0, alen-1);

	write_file_trailer();
}


void write_file_header()
{
	printf (
			"/*\n"
			" * grids.h - all possible puzzle grids for suko solver\n"
			" *\n"
			" * DO NOT EDIT. Generated by " PROGRAM " v. " VERSION "\n"
			" *\n"
			" */\n"
			"\n"
			"#ifndef _GRIDS_H\n"
			"#define _GRIDS_H\n"
			"\n"
			"/*\n"
			" * Contains 9! permutations or 362880 rows, each row\n"
			" * a unique permutation.  Solver just runs through \n"
			" * the list to find a permutation that matches the\n"
			" * suko puzzle's parameters.\n"
			" *\n"
			" */\n"
			"#define _GRID_PERMUTATIONS {\\\n"
	       );
}

void writeout(int a[], int width)
{
	char * end_of_line= "},\\\n";

	if (++permutation_knt >= PERMUTATIONS_MAX)
			end_of_line= "}}\n";

	printf("    {");

		
	for (int i = 0; i < 9; i++)
		printf("%d%s", a[i], (i+1)%width ? "," : end_of_line);
}


void permute(int a[], int left, int right)
{
	if (left == right)
		writeout (a, 9);
	else
		for (int i = left; i <= right; i++) {
			swap_i (a[left], a[i]);
			permute (a, left+1, right);
			swap_i (a[left], a[i]);
		}
}

void write_file_trailer()
{
	printf ("\n\n#endif /* grids.h */\n");
}
